channels:
  - conda-forge

dependencies:
  # https://anaconda.org/search
  - gtk3
  - xorg-libx11
  - xorg-libxcursor
  - xorg-libxdamage
  - xorg-libxcomposite
  - xorg-libxrandr
  - xorg-libxinerama
  - pyyaml
  - firefox==113.0
  - geckodriver=0.33.0
  - python=3.10.12
  - pip=23.2.1
  - pip:
      # Old enough versions to support old style headlessfirefox
      - rpaframework==22.5.2
      - robotframework-seleniumtestability==2.1.0
      - selenium==4.8.3
