channels:
  - conda-forge
  - cf-staging

dependencies:
  # https://anaconda.org/search
  - gtk3
  - xorg-libx11
  - xorg-libxcursor
  - xorg-libxdamage
  - xorg-libxcomposite
  - xorg-libxrandr
  - xorg-libxinerama
  - firefox=94.0.2
  - geckodriver=0.30.0
  - python=3.9.7
  - pip=21.3.1
  - pip:
      - rpaframework==11.6.4
      - robotframework-seleniumtestability==1.1.0
