channels:
  - conda-forge

dependencies:
  # https://anaconda.org/search
  - firefox=79.0
  - geckodriver=0.26.0
  - python=3.8.8
  - pip=21.1.3
  - pip:
      - rpaframework==10.4.0
      - robotframework-seleniumtestability==1.1.0
